// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command gen-sdk-datalog writes the baseline Datalog a mesh member evaluates
// when it authorizes a caller, as api/datalog.go defines it, into the JSON
// artifact the native SDKs embed. Go stays the source of truth;
// hack/verify-sdk-generated.sh fails when the artifact is stale.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/google/sam/api"
)

type artifact struct {
	Comment string `json:"_comment"`
	api.DatalogSources
	FactService         string   `json:"fact_service"`
	FactConnectionPeer  string   `json:"fact_connection_peer_id"`
	FactMethod          string   `json:"fact_method"`
	FactPath            string   `json:"fact_path"`
	FactTime            string   `json:"fact_time"`
	FactRole            string   `json:"fact_role"`
	FactTargetFact      string   `json:"fact_target_fact"`
	MarkerTerm          string   `json:"marker_term"`
	SystemNamespace     string   `json:"system_namespace"`
	BindingPrefixes     []string `json:"binding_member_prefixes"`
	SystemAuthenticated string   `json:"system_authenticated_member"`
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gen-sdk-datalog <output.json> <output.ts>")
		os.Exit(2)
	}
	a := artifact{
		Comment:             "Generated by hack/gen-sdk-datalog from api/datalog.go; do not edit.",
		DatalogSources:      api.BaselineSources,
		FactService:         api.FactService,
		FactConnectionPeer:  api.FactConnectionPeerID,
		FactMethod:          api.FactMethod,
		FactPath:            api.FactPath,
		FactTime:            api.FactTime,
		FactRole:            api.FactRole,
		FactTargetFact:      api.FactTargetFact,
		MarkerTerm:          api.MarkerTerm.String(),
		SystemNamespace:     api.SystemNamespace,
		BindingPrefixes:     api.BindingMemberPrefixes(),
		SystemAuthenticated: api.SystemAuthenticated,
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(a); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(os.Args[1], buf.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	ts := "// Code generated by hack/gen-sdk-datalog from api/datalog.go; DO NOT EDIT.\n\n" +
		"/** The Datalog a provider evaluates against a caller's biscuit. */\n" +
		"export const BASELINE_DATALOG = " + strings.TrimRight(buf.String(), "\n") + " as const;\n"
	if err := os.WriteFile(os.Args[2], []byte(ts), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
