# Stage 1: Build
FROM golang:1.27.1@sha256:3680233e3204827fbdc66088528ae6d4b3d034f51d03a99d454f6de034888244 AS builder
RUN apt-get update && apt-get install -y gcc libc-dev
WORKDIR /app
COPY cmd/nano-init/go.mod cmd/nano-init/go.sum ./
RUN go mod download
COPY cmd/nano-init/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -ldflags="-s -w" -o nano-init .

# Stage 2: Final
FROM gcr.io/distroless/base:nonroot@sha256:a0d70d6a97cd697d9362bc2aae4a6560dd65817e365d0043b07325a97975dc91
COPY --from=builder --chown=nonroot:nonroot /app/nano-init /
USER nonroot:nonroot
ENTRYPOINT ["/nano-init"]
